### ISSUE TITLE
not work for me (

### ISSUE THREAD

**Issue by tvortsa** [richardeschloss/les#38]
![image](https://user-images.githubusercontent.com/78345/83545386-cb286e00-a507-11ea-883c-178d7e52e987.png)

**Comment by richardeschloss** [comment]
Hi friend, I'll be happy to help. It appears that you're trying to run the server after having cloned this repo, and trying to run the source files, in which case you need to make sure you install all the development dependencies (see `devDependencies` in package.json). Most likely you are trying to run the source files without having babel core. Or, you have the devDependenices, but you're running node instead of babel-node, in which case you would need to run `npm run dev`. If you want to use node instead, you can run the built files in `bin` like `node bin/server.js`

**Comment by tvortsa** [comment]
thank you!
